### ISSUE TITLE
Exception calling playMedia: java.lang.NullPointerException

### ISSUE THREAD

**Issue by vkhazin** [ConnectSDK/Connect-SDK-Cordova-API-Sampler#1]
Google sdk extras are from v7
Cordova 4.1.2
Android-21

Error when calling: mediaPlayer.playMedia

Object {message: "Exception calling playMedia: java.lang.NullPointerException", detail: "com.connectsdk.cordova.JSCommandDispatcher$Dispatc…calling playMedia: java.lang.NullPointerException"}
detail: "com.connectsdk.cordova.JSCommandDispatcher$DispatcherException: Exception calling playMedia: java.lang.NullPointerException"
message: "Exception calling playMedia: java.lang.NullPointerException"

**Comment by Andolamin** [comment]
This was fixed in the 1.6.0 release
